// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgMWoToW1gjmPZmz2AxGPFYntSSqqTD7g',
    appId: '1:40504650061:web:76cbcfc98d932b1eaa2f04',
    messagingSenderId: '40504650061',
    projectId: 'authentication-todo-flutter',
    authDomain: 'authentication-todo-flutter.firebaseapp.com',
    storageBucket: 'authentication-todo-flutter.appspot.com',
    measurementId: 'G-K9N8V3Z2LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaBTBvlj1r3rByMqY6kHrgNAI20Hx25ds',
    appId: '1:40504650061:android:006f26bac0e38400aa2f04',
    messagingSenderId: '40504650061',
    projectId: 'authentication-todo-flutter',
    storageBucket: 'authentication-todo-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBotIIn2GO_lwmn3l6RaagseN6EyW7BOZA',
    appId: '1:40504650061:ios:dbae94d365cf7a3caa2f04',
    messagingSenderId: '40504650061',
    projectId: 'authentication-todo-flutter',
    storageBucket: 'authentication-todo-flutter.appspot.com',
    iosClientId: '40504650061-3jn7jg973oec9imlv4qgsugdbse9rq3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBotIIn2GO_lwmn3l6RaagseN6EyW7BOZA',
    appId: '1:40504650061:ios:dbae94d365cf7a3caa2f04',
    messagingSenderId: '40504650061',
    projectId: 'authentication-todo-flutter',
    storageBucket: 'authentication-todo-flutter.appspot.com',
    iosClientId: '40504650061-3jn7jg973oec9imlv4qgsugdbse9rq3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );
}
